DEBUG 2021-02-03 17:05:00.582 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-02-03 17:05:00.582 UTC: 	 Running on: Linux hammer-c000 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-02-03 17:05:00.582 UTC: 	 Executing command: 'submit'
DEBUG 2021-02-03 17:05:00.583 UTC: 	 Found CRAB cache file /home/dkondra/.crab3
ERROR 2021-02-03 17:05:00.584 UTC: 	 CRAB configuration file crabConfig.py not found.
ERROR 2021-02-03 17:05:00.585 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 312, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 52, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crabConfig.py not found.
INFO 2021-02-03 17:05:00.587 UTC: 	 Log file is /home/dkondra/muon-hlt-forRun3/CMSSW_10_2_6/src/MuonHLTNtuples/Tools/crab.log
DEBUG 2021-02-03 19:56:17.091 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-02-03 19:56:17.092 UTC: 	 Running on: Linux hammer-c000 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-02-03 19:56:17.092 UTC: 	 Executing command: 'submit'
DEBUG 2021-02-03 19:56:17.092 UTC: 	 Found CRAB cache file /home/dkondra/.crab3
INFO 2021-02-03 19:56:17.095 UTC: 	 Will use CRAB configuration file CrabConfig_MC.py
DEBUG 2021-02-03 19:56:17.095 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-02-03 19:56:17.106 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-02-03 19:56:17.106 UTC: 	 Working area '/home/dkondra/muon-hlt-forRun3/CMSSW_10_2_6/src/MuonHLTNtuples/Tools/muonHLTtest_Run2_DYJets_default/crab_muonHLTtest_Run2_DYJets_default' already exists 
Please change the requestName in the config file
ERROR 2021-02-03 19:56:17.106 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/home/dkondra/muon-hlt-forRun3/CMSSW_10_2_6/src/MuonHLTNtuples/Tools/muonHLTtest_Run2_DYJets_default/crab_muonHLTtest_Run2_DYJets_default' already exists 
Please change the requestName in the config file
INFO 2021-02-03 19:56:17.110 UTC: 	 Log file is /home/dkondra/muon-hlt-forRun3/CMSSW_10_2_6/src/MuonHLTNtuples/Tools/crab.log
DEBUG 2021-02-06 19:05:28.640 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-02-06 19:05:28.641 UTC: 	 Running on: Linux hammer-c000 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-02-06 19:05:28.641 UTC: 	 Executing command: 'status'
DEBUG 2021-02-06 19:05:28.641 UTC: 	 Found CRAB cache file /home/dkondra/.crab3
ERROR 2021-02-06 19:05:28.644 UTC: 	 Cannot find .requestcache file in CRAB project directory /home/dkondra/muon-hlt-forRun3/CMSSW_10_2_6/src/MuonHLTNtuples/Tools/muonHLTtest_Run2_DYJets_default_SF10
ERROR 2021-02-06 19:05:28.644 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 632, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 494, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /home/dkondra/muon-hlt-forRun3/CMSSW_10_2_6/src/MuonHLTNtuples/Tools/muonHLTtest_Run2_DYJets_default_SF10
INFO 2021-02-06 19:05:28.647 UTC: 	 Log file is /home/dkondra/muon-hlt-forRun3/CMSSW_10_2_6/src/MuonHLTNtuples/Tools/crab.log
DEBUG 2021-02-15 19:14:26.999 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-02-15 19:14:26.999 UTC: 	 Running on: Linux hammer-c000 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-02-15 19:14:26.999 UTC: 	 Executing command: 'submit'
DEBUG 2021-02-15 19:14:27.000 UTC: 	 Found CRAB cache file /home/dkondra/.crab3
DEBUG 2021-02-15 19:51:25.614 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-02-15 19:51:25.614 UTC: 	 Running on: Linux hammer-c000 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-02-15 19:51:25.615 UTC: 	 Executing command: 'submit'
DEBUG 2021-02-15 19:51:25.615 UTC: 	 Found CRAB cache file /home/dkondra/.crab3
INFO 2021-02-15 19:51:25.616 UTC: 	 Will use CRAB configuration file CrabConfig_Data.py
DEBUG 2021-02-15 19:51:25.616 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-02-15 19:51:25.619 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-02-15 19:51:25.620 UTC: 	 Working area '/home/dkondra/muon-hlt-forRun3/CMSSW_10_2_6/src/MuonHLTNtuples/Tools/muonHLTtest_Run2_SingleMuonB_default/crab_muonHLTtest_Run2_SingleMuonB_default' already exists 
Please change the requestName in the config file
ERROR 2021-02-15 19:51:25.620 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/home/dkondra/muon-hlt-forRun3/CMSSW_10_2_6/src/MuonHLTNtuples/Tools/muonHLTtest_Run2_SingleMuonB_default/crab_muonHLTtest_Run2_SingleMuonB_default' already exists 
Please change the requestName in the config file
INFO 2021-02-15 19:51:25.621 UTC: 	 Log file is /home/dkondra/muon-hlt-forRun3/CMSSW_10_2_6/src/MuonHLTNtuples/Tools/crab.log
DEBUG 2021-02-15 20:36:49.531 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-02-15 20:36:49.532 UTC: 	 Running on: Linux hammer-c000 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-02-15 20:36:49.532 UTC: 	 Executing command: 'submit'
DEBUG 2021-02-15 20:36:49.532 UTC: 	 Found CRAB cache file /home/dkondra/.crab3
INFO 2021-02-15 20:36:49.533 UTC: 	 Will use CRAB configuration file CrabConfig_Data.py
DEBUG 2021-02-15 20:36:49.533 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-02-15 20:36:49.544 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-02-15 20:36:49.544 UTC: 	 Working area '/home/dkondra/muon-hlt-forRun3/CMSSW_10_2_6/src/MuonHLTNtuples/Tools/muonHLTtest_Run2_SingleMuonD_default/crab_muonHLTtest_Run2_SingleMuonD_default' already exists 
Please change the requestName in the config file
ERROR 2021-02-15 20:36:49.544 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/home/dkondra/muon-hlt-forRun3/CMSSW_10_2_6/src/MuonHLTNtuples/Tools/muonHLTtest_Run2_SingleMuonD_default/crab_muonHLTtest_Run2_SingleMuonD_default' already exists 
Please change the requestName in the config file
INFO 2021-02-15 20:36:49.546 UTC: 	 Log file is /home/dkondra/muon-hlt-forRun3/CMSSW_10_2_6/src/MuonHLTNtuples/Tools/crab.log
DEBUG 2021-02-20 19:03:22.568 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-02-20 19:03:22.569 UTC: 	 Running on: Linux hammer-c000 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-02-20 19:03:22.569 UTC: 	 Executing command: 'submit'
DEBUG 2021-02-20 19:03:22.569 UTC: 	 Found CRAB cache file /home/dkondra/.crab3
INFO 2021-02-20 19:03:22.570 UTC: 	 Will use CRAB configuration file CrabConfig_MC.py
DEBUG 2021-02-20 19:03:22.570 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-02-20 19:03:22.582 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-02-20 19:03:22.582 UTC: 	 Task requests 8000 MB of memory, above the allowed maximum of 5000 for a 1 core(s) job.

The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2021-02-20 19:03:22.582 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 312, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 95, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Task requests 8000 MB of memory, above the allowed maximum of 5000 for a 1 core(s) job.

The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2021-02-20 19:03:22.584 UTC: 	 Log file is /home/dkondra/muon-hlt-forRun3/CMSSW_10_2_6/src/MuonHLTNtuples/Tools/crab.log
